### ISSUE TITLE
RuntimeException: Invalid length given for storage, got: 36 but expected: 37

### ISSUE THREAD

**Issue by mibby** [xuancat0208/ViewDistanceCat#1]
Tuinity dev 393 (Paper 1.16.3)
https://github.com/Spottedleaf/Tuinity/actions
ViewDistanceCat v4.4.4
XuanCatAPI 14~16-1.0.5 compiled as of commit https://github.com/xuancat0208/XuanCatAPI/commit/151e5aa3293fbffeaaa780cbece8d54072f073cc

@xuancat0208 Came across this error in my logs. Occurred a handful of times, sometimes spamming.

```
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: java.lang.RuntimeException: Invalid length given for storage, got: 36 but expected: 37
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at net.minecraft.server.v1_16_R2.DataBits.<init>(DataBits.java:38)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at net.minecraft.server.v1_16_R2.HeightMap.a(HeightMap.java:137)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at net.minecraft.server.v1_16_R2.ProtoChunk.a(ProtoChunk.java:312)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.world.CodeExtendChunkRegionLoader.loadProtoChunk(CodeExtendChunkRegionLoader.java:87)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.world.CodeExtendWorld.parseChunkNBT(CodeExtendWorld.java:153)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at xuan.cat.xuancatapi.code.v1_16_R2.nms.world.CodeExtendRegion.getChunk(CodeExtendRegion.java:53)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at xuan.cat.viewdistancecat.code.ChunkServer.asyncTick(ChunkServer.java:307)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at xuan.cat.viewdistancecat.code.ChunkServer$Multithreaded.tick(ChunkServer.java:128)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
[14:07:56] [ViewDistanceCat AsyncTick thread #0/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
```

Config
```
max-view-distance: 32
server-view-distance: -1
async-thread-amount: 5
read-server-cached-chunk: false
can-generate-chunk: false
automatic-speed-adjustment-scheme: HIGHEST
tick-player-send-chunk: 3
tick-server-send-chunk: -1
player-delay: 2000
prevent-xray:
  enable: false
  conversion-list:
    STONE:
      - COAL_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - GOLD_ORE
      - IRON_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
    NETHERRACK:
      - NETHER_QUARTZ_ORE
world-blacklist:
  - disabled
player-independent-permissions: false
pressure-test: false
```

**Comment by xuancat0208** [comment]
Sorry, the plugin decided to stop maintenance
Or try to paper no-tick-view-distance

**Comment by mibby** [comment]
Sorry to hear that. Paper no-ticket-view-distance is much laggier than ViewDistanceCat. :(

**Comment by xuancat0208** [comment]
Paper no-ticket-view-distance is ruined this plugin, it is no longer needed by everyone, so there is no reason to update
(ーー゛)
